### PR TITLE
use tailscale cert manager with tailscale-proxy command

### LINKED ISSUE #27: tailscale-proxy fails with TLS
When you use tailscale-proxy with HTTPS/TLS, it tries to start QUIC and then fails:

```
{"level":"warn","ts":1703777283.5945904,"logger":"admin","msg":"admin endpoint disabled"}
{"level":"info","ts":1703777283.620156,"logger":"http.auto_https","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"proxy","https_port":443}
{"level":"info","ts":1703777283.620855,"logger":"http.auto_https","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"proxy"}
{"level":"info","ts":1703777283.620443,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc00021e000"}
{"level":"warn","ts":1703777283.6335611,"logger":"tls","msg":"storage cleaning happened too recently; skipping for now","storage":"FileStorage:/data/caddy","instance":"7f43f41d-9b67-4aae-a7dc-563d96f88d7b","try_again":1703863683.63346,"try_again_in":86399.99999947}
{"level":"info","ts":1703777283.635115,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"info","ts":1703777283.676397,"logger":"http","msg":"enabling HTTP/3 listener","addr":"franklin:443"}
{"level":"info","ts":1703777283.6845386,"logger":"tls.cache.maintenance","msg":"stopped background certificate maintenance","cache":"0xc00021e000"}
Error: loading new config: http app module: start: starting HTTP/3 QUIC listener: listen udp 100.84.250.36:443: bind: cannot assign requested address
```

This is from inside a container:

```
ARG CADDY_VERSION=latest

FROM docker.io/library/caddy:builder AS build
ENV XCADDY_SKIP_CLEANUP=1
RUN xcaddy build \
    --with github.com/tailscale/caddy-tailscale \
    $CADDY_VERSION

FROM docker.io/library/caddy
COPY --from=build /usr/bin/caddy /usr/bin/caddy
```

Using the command `['/usr/bin/caddy', 'tailscale-proxy', '--from', 'tailscale/myhost:443', '--to', 'backend:7071']`

### PR DESCRIPTION
**Pull request by willnorris**
Instruct caddy to use the tailscale cert manager.  Also add a --debug flag to enable debug logging with the tailscale-proxy command.

Also remove a lingering `auto_https off` config in one of our examples.

Fixes #27

### CODE REVIEW

File: command.go [hunk 1]
```diff
@@ -216,6 +227,17 @@ func cmdTailscaleProxy(fs caddycmd.Flags) (int, error) {
 		},
 		AppsRaw: appsRaw,
 	}
+	if debug {
```
Comment (irbekrm) [inline command.go:230]: Question: is the caddy config generated here persisted across restarts? If it is, then users would have no way to unset the debug flag except for by deleting the config

Comment (willnorris) [reply command.go:230]: no, this config is entirely in memory.  It's not persisted anywhere.

In hindsight, I'm not actually sure how useful this `tailscale-proxy` subcommand really is compared to just creating a pretty simple caddyfile that does the same thing.  It was something I added pretty on, mostly just to see if I could 🤷🏻

Comment (irbekrm) [reply command.go:230]: would the proxy subcommand be useful for the Dockerfile? https://github.com/tailscale/caddy-tailscale/issues/14

**Review by irbekrm — APPROVED** [review]

File: command.go (hunk 1 above)
Comment (willnorris) [reply command.go:230]: yeah, possibly.  If the Dockerfile just provided a caddy binary with the tailscale plugin compiled in, then you could use that to run the proxy.  I'll go ahead and add that to the v1 milestone... seems worth doing.
