### PR TITLE
Fix auth.go not finding the tsnet.Listener.

### LINKED ISSUE #68: Failed to connect to local Tailscale daemon - /var/run/tailscale/tailscaled.sock: connect: no such file or directory
I feel like I'm missing something obvious here. I know when I manually install the tailscale client (as opposed to using the caddy-tailscale module) that `/var/run/tailscale/tailscaled.sock` is the correct path. I see when I ssh into the server that the `/var/run/tailscale` directory does not exist. But the Caddy logs seem to show the server connecting to the tailscale client. Is there a step I'm missing that I should be doing to set this up correctly?

The Tailscale logs when Caddy boots up:
```json
{"level":"info","ts":1718132344.4524896,"logger":"tailscale","msg":"tsnet running state path /data/tailscale/my-node/tailscaled.state"}
{"level":"info","ts":1718132344.453898,"logger":"tailscale","msg":"tsnet starting with hostname \"my-node\", varRoot \"/data/tailscale/my-node\""}
{"level":"info","ts":1718132345.4562378,"logger":"tailscale","msg":"LocalBackend state is NeedsLogin; running StartLoginInteractive..."}
{"level":"info","ts":1718132350.4583023,"logger":"tailscale","msg":"AuthLoop: state is Running; done"}
```

`foo.bar.com` has A and AAAA records with private IP values from the Tailscale device `my-node`.
The error after making a request in browser to `http://foo.bar.com`:
```json
{
  "level": "error",
  "ts": 1718132857.5938432,
  "logger": "http.handlers.authentication",
  "msg": "auth provider returned error",
  "provider": "tailscale",
  "error": "Failed to connect to local Tailscale daemon for /localapi/v0/whois; not running? Error: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory"
}
```

Request which shows up in logs right after the error:
```json
{
  "level": "info",
  "ts": 1718150968.8068163,
  "logger": "http.log.access.tailscale",
  "msg": "handled request",
  "request": {
    "remote_ip": "100.106.231.73",
    "remote_port": "60590",
    "client_ip": "100.106.231.73",
    "proto": "HTTP/1.1",
    "method": "GET",
    "host": "foo.bar.com",
    "uri": "/",
    "headers": {
      "Accept": [
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
      ],
      "Accept-Encoding": [
        "gzip, deflate"
      ],
      "Accept-Language": [
        "en-US,en;q=0.9"
      ],
      "Connection": [
        "keep-alive"
      ],
      "Dnt": [
        "1"
      ],
      "Upgrade-Insecure-Requests": [
        "1"
      ],
      "User-Agent": [
        "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
      ]
    }
  },
  "bytes_read": 0,
  "user_id": "",
  "duration": 0.001536612,
  "size": 0,
  "status": 401,
  "resp_headers": {
    "Server": [
      "Caddy"
    ]
  }
}
```

Dockerfile:
```dockerfile
RUN /app/caddy/xcaddy build v2.8.4 \
    --with github.com/tailscale/caddy-tailscale \
    --with github.com/caddy-dns/route53 \
    --output /usr/bin/caddy

RUN chmod +x /usr/bin/caddy

CMD ["caddy", "run", "--config", "/config/caddy/caddy.json"]
```

Caddyfile:
```caddyfile
{
  debug
  auto_https off
  tailscale {
    ephemeral
    auth_key "{env.TS_AUTHKEY}"
    state_dir "/data/tailscale"
  }
}

foo.bar.com:80 {
  bind tailscale/my-node
  tailscale_auth

  templates
  respond `Hello, {placeholder "http.auth.user.id"}}`
}
```

Caddy json config:
```json
{
  "logging": {
    "logs": {
      "default": {
        "level": "DEBUG"
      }
    }
  },
  "apps": {
    "http": {
      "servers": {
        "srv0": {
          "listen": [
            "tailscale/my-node:80"
          ],
          "routes": [
            {
              "match": [
                {
                  "host": [
                    "foo.bar.com"
                  ]
                }
              ],
              "handle": [
                {
                  "handler": "subroute",
                  "routes": [
                    {
                      "handle": [
                        {
                          "handler": "authentication",
                          "providers": {
                            "tailscale": {}
                          }
                        },
                        {
                          "handler": "templates"
                        },
                        {
                          "body": "Hello, {placeholder \"http.auth.user.id\"}}",
                          "handler": "static_response"
                        }
                      ]
                    }
                  ]
                }
              ],
              "terminal": true
            }
          ],
          "automatic_https": {
            "disable": true
          }
        }
      }
    },
    "tailscale": {
      "auth_key": "{env.TS_AUTHKEY}",
      "ephemeral": true,
      "state_dir": "/data/tailscale"
    }
  }
}
```

### PR DESCRIPTION
**Pull request by beep-beep-beep-boop**
This fixes #68 

`auth.go` was treating the listener as if it was a `tsnet.Listener`, but it was actually a `tsServerListener` which had a member (`Listener`) that implemented `tsnet.Listener`. This caused it to fall-through and try to authenticate the request through a locally-running `tailscaled`, which would fail if caddy was running in a container without one.

I'm not very familiar with go so IDK if there's a less messy-looking way to do this.

### CODE REVIEW

**Comment by beep-beep-beep-boop** [comment]
okay, this doesn't completely fix it. the issue still happens when trying to connect via https to the `.ts.net` domain. everything else will work, including the http `.ts.net` domain. (although if you put the https domain itself in the caddy file instead of `:443` it seems like it tries to redirect to the https one which will essentially make the http `.ts.net` stop working as well.)

if you remove the `tailscale_auth` directive from the https route in the caddyfile it will work fine.

so this won't work:
```caddy
https://caddytest.abc.ts.net {
  bind tailscale/caddytest
  tailscale_auth # this is causing the issue
  templates
  respond `Hello, {{placeholder "http.auth.user.id"}}`
}
```

but this will (but it won't authenticate):
```caddy
https://caddytest.abc.ts.net {
  bind tailscale/caddytest
  templates
  respond `Hello, {{placeholder "http.auth.user.id"}}`
}
```

**Comment by willnorris** [comment]
okay, so the problem is that ever since f2562ba, we no longer just have a `tsnet.listener`.  We now have a `tsnet.listener` wrapped in a `[crypto/tls].listener` wrapped in a `caddyhttp.http2Listener`, and neither of the latter two expose methods to unwrap them and get the internal listener.  We could send a patch to caddy to add an `Unwrap() net.Listener` method on `caddyhttp.http2Listener`, but `tls.listener` is a lot more challenging.

@mholt, how gross would it be to have something like:

```go
type wrappedListener struct {
	net.Listener
	wrapped net.Listener
}

func (h *wrappedListener) Unwrap() net.Listener {
	return h.wrapped
}
```
and then app.Start has something like:

``` go
	if useTLS {
		// create TLS listener - this enables and terminates TLS
		tlsln := tls.NewListener(ln, tlsCfg)
		ln = &wrappedListener{Listener: tlsln, wrapped: ln}
		// ...
	}
```

I just tested this, and along with an `Unwrap` method on `caddyhttp.http2Listener`, this works to let me recursively unwrap to get to the underlying listener.

**Comment by beep-beep-beep-boop** [comment]
I think the issue is that the tls `tsnetServerListener` is getting wrapped in two other objects by caddy.

```go
// create TLS listener - this enables and terminates TLS
ln = tls.NewListener(ln, tlsCfg)
```

```go
// handle http2 if use tls listener wrapper
if useTLS {
	http2lnWrapper := &http2Listener{
		Listener: ln,
		server:   srv.server,
		h2server: h2server,
	}
	srv.h2listeners = append(srv.h2listeners, http2lnWrapper)
	ln = http2lnWrapper
}
```
([here](https://github.com/caddyserver/caddy/blob/fab6375a8bebd952abc80e63fa31b648ae1ebc0b/modules/caddyhttp/app.go#L455) and [here](https://github.com/caddyserver/caddy/blob/fab6375a8bebd952abc80e63fa31b648ae1ebc0b/modules/caddyhttp/app.go#L489))

so the resulting listener ends up being
```
net.Listener(*github.com/caddyserver/caddy/v2/modules/caddyhttp.http2Listener) *{
    cnt: 0, Listener: net.Listener(*crypto/tls.listener) *{
        Listener: net.Listener(*github.com/tailscale/caddy-tailscale.tsnetServerListener) ... etc
```

I don't think we can get `tsnetServerListener` out of this with type assertations because `caddyhttp.http2Listener` is private. I guess maybe we could use reflection but that sounds kinda cursed.

**Comment by beep-beep-beep-boop** [comment]
I was thinking about using reflection to get to it. having a way to do it built into caddy would be better though i think.

**Comment by beep-beep-beep-boop** [comment]
I updated the PR to use reflection for now but doing it on caddy's end is probably a better permanent solution.

**Comment by mholt** [comment]
@willnorris We could do that, but like you mentioned, that chain would stop with a listener out of our control (like tls.Listener). Is the unwrapping needed only in this specific case?

**Comment by willnorris** [comment]
> @willnorris We could do that, but like you mentioned, that chain would stop with a listener out of our control (like tls.Listener). Is the unwrapping needed only in this specific case?

Yes, the `wrappedListener` type is only needed for the case of listeners out of caddy's control.  I don't know if tls.Listener is the only example of that... that's just the one at play in this specific instance.

**Comment by mholt** [comment]
What if we stick with the current solution (reflection -- not as ugly as I'd have thought!) and if other use cases start showing up, we can consider generalizing a solution upstream in Caddy?

**Comment by willnorris** [comment]
The proposed changes to caddy are quite minimal as well, and far cleaner than having to resort to reflection.  Though I do understand that we're likely one of the only ones using `caddyhttp.Server.Listeners()`, so this would be a change in a highly used code path for a very small number of users.

**Comment by mholt** [comment]
True -- and to clarify, I'm not opposed to that change in Caddy (someday, if needed) -- because it's so minimal. I'm just thinking that for now, let's see if this can work and if we need it to generalize then we can make the change :+1:

File: auth.go [hunk 1]
```diff
@@ -40,6 +42,39 @@ func (Auth) CaddyModule() caddy.ModuleInfo {
 	}
 }
 
+// findTsnetListener recursively searches ln for embedded child net.Listener structs
+// until it finds the tsnetListener or runs out.
+// the 2nd return value is true if it was found, false if it wasn't.
```
Comment (willnorris) [inline auth.go:47]:
```suggestion
// the 2nd return value is true if it was found, false if it wasn't.
//
// In the future consider alternative approach if Caddy supports unwrapping listeners.
// See discussion in https://github.com/tailscale/caddy-tailscale/pull/70
```

**Review by willnorris — COMMENTED** [review]
@beep-beep-beep-boop let's add a note on this new func to revisit in the future if and when Caddy support unwrapping listeners.   Otherwise, this LGTM

**Comment by willnorris** [comment]
I pushed a new commit to go ahead and add the `wrappedListener` interface and use it when present, then use reflection as a fallback.

**Review by willnorris — APPROVED** [review]
