### PR TITLE
transport: add TLS support

### LINKED ISSUE #25: Question: How to correctly configure reverse_proxy for a TLS upstream
Hello!

Thank you for this incredible project.

Consider following snippet:
```
:80 {
   reverse_proxy https://proxmoxvox.ts.net:8006 {
       transport tailscale
   }
}
```
Error message:
```
Error: adapting config using caddyfile: parsing caddyfile tokens for 'reverse_proxy': upstreams are configured for HTTPS but transport module does not support TLS: *tscaddy.TailscaleCaddyTransport, at Caddyfile:4
```

I understand that this limitation related to https://github.com/tailscale/caddy-tailscale#https-support  but what would be the right syntax?

Thanks!

### LINKED ISSUE #27: tailscale-proxy fails with TLS
When you use tailscale-proxy with HTTPS/TLS, it tries to start QUIC and then fails:

```
{"level":"warn","ts":1703777283.5945904,"logger":"admin","msg":"admin endpoint disabled"}
{"level":"info","ts":1703777283.620156,"logger":"http.auto_https","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"proxy","https_port":443}
{"level":"info","ts":1703777283.620855,"logger":"http.auto_https","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"proxy"}
{"level":"info","ts":1703777283.620443,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc00021e000"}
{"level":"warn","ts":1703777283.6335611,"logger":"tls","msg":"storage cleaning happened too recently; skipping for now","storage":"FileStorage:/data/caddy","instance":"7f43f41d-9b67-4aae-a7dc-563d96f88d7b","try_again":1703863683.63346,"try_again_in":86399.99999947}
{"level":"info","ts":1703777283.635115,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"info","ts":1703777283.676397,"logger":"http","msg":"enabling HTTP/3 listener","addr":"franklin:443"}
{"level":"info","ts":1703777283.6845386,"logger":"tls.cache.maintenance","msg":"stopped background certificate maintenance","cache":"0xc00021e000"}
Error: loading new config: http app module: start: starting HTTP/3 QUIC listener: listen udp 100.84.250.36:443: bind: cannot assign requested address
```

This is from inside a container:

```
ARG CADDY_VERSION=latest

FROM docker.io/library/caddy:builder AS build
ENV XCADDY_SKIP_CLEANUP=1
RUN xcaddy build \
    --with github.com/tailscale/caddy-tailscale \
    $CADDY_VERSION

FROM docker.io/library/caddy
COPY --from=build /usr/bin/caddy /usr/bin/caddy
```

Using the command `['/usr/bin/caddy', 'tailscale-proxy', '--from', 'tailscale/myhost:443', '--to', 'backend:7071']`

### PR DESCRIPTION
**Pull request by willnorris**
Implement reverseproxy.TLSTransport.  We go ahead and store the provided TLSConfig object, but for now we only use it to indicate that we should use TLS.  We don't actually use any of the provided values to configure the client.

Fixes #25

### CODE REVIEW

File: transport.go [hunk 1]
```diff
@@ -64,14 +69,30 @@ func (t *Transport) Cleanup() error {
...
+func (h Transport) TLSEnabled() bool {
+	return h.TLS != nil
+}
+
+// EnableTLS enables TLS on the transport.
+func (h *Transport) EnableTLS(config *reverseproxy.TLSConfig) error {
+	h.TLS = config
+	return nil
+}
+
```
Comment (irbekrm) [inline transport.go:91]: So this just makes our transport implement reverseproxy.TLSTransport 👍🏼

Comment (irbekrm) [reply transport.go:91]: (oh, you also had that in the commit message)
